# Generated by Django 4.2.5 on 2023-12-27 14:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('boy', 'boy'), ('girl', 'girl'), ('infant', 'infant')], default='boy', max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyflamingo.category')),
            ],
        ),
        migrations.CreateModel(
            name='DressVarients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('extrasmall', 'extrasmall'), ('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('extralarge', 'extralarge')], default='small', max_length=200)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyflamingo.dress')),
            ],
        ),
        migrations.CreateModel(
            name='Stationary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('powder', 'powder'), ('kajol', 'kajol'), ('shamboo', 'shamboo'), ('bottle', 'bottle'), ('brush', 'brush'), ('pambers', 'pambers'), ('wipes', 'wipes'), ('bag', 'bag'), ('baby-bed', 'baby-bed')], default='powder', max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyflamingo.category')),
            ],
        ),
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('electric-toy', 'electric-toy'), ('battery-toy', 'battery-toy'), ('plastic-toy', 'palstic-toy')], default='plastic-toy', max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyflamingo.category')),
            ],
        ),
        migrations.CreateModel(
            name='ToyVarients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('extrasmall', 'extrasmall'), ('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('extralarge', 'extralarge')], default='small', max_length=200)),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyflamingo.toys')),
            ],
        ),
        migrations.CreateModel(
            name='StationaryVarients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('extrasmall', 'extrasmall'), ('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('extralarge', 'extralarge')], default='small', max_length=200)),
                ('stationary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyflamingo.stationary')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewstoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=300)),
                ('toy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='babyflamingo.toys')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewsstationary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=300)),
                ('stationary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='babyflamingo.stationary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewsdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=300)),
                ('dress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='babyflamingo.dress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orderstoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order-placed', 'order-placed'), ('cancelled', 'cancelled'), ('dispatced', 'dispatched'), ('in-transit', 'in-transit'), ('delivered', 'delivered')], default='order-placed', max_length=200)),
                ('orderd_date', models.DateTimeField(auto_now_add=True)),
                ('expected_date', models.DateField(null=True)),
                ('address', models.CharField(max_length=200)),
                ('toyvarient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyflamingo.toyvarients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ordersstationary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order-placed', 'order-placed'), ('cancelled', 'cancelled'), ('dispatced', 'dispatched'), ('in-transit', 'in-transit'), ('delivered', 'delivered')], default='order-placed', max_length=200)),
                ('orderd_date', models.DateTimeField(auto_now_add=True)),
                ('expected_date', models.DateField(null=True)),
                ('address', models.CharField(max_length=200)),
                ('stationaryvarient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyflamingo.stationaryvarients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ordersdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order-placed', 'order-placed'), ('cancelled', 'cancelled'), ('dispatced', 'dispatched'), ('in-transit', 'in-transit'), ('delivered', 'delivered')], default='order-placed', max_length=200)),
                ('orderd_date', models.DateTimeField(auto_now_add=True)),
                ('expected_date', models.DateField(null=True)),
                ('address', models.CharField(max_length=200)),
                ('dressvarient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyflamingo.dressvarients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offerstoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('toyvarient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyflamingo.toyvarients')),
            ],
        ),
        migrations.CreateModel(
            name='Offersstationary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('stationaryvarient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyflamingo.stationaryvarients')),
            ],
        ),
        migrations.CreateModel(
            name='Offersdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('dressvarient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babyflamingo.dressvarients')),
            ],
        ),
        migrations.CreateModel(
            name='Cartstoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in-cart', 'in-cart'), ('order-placed', 'order-placed'), ('cancelled', 'cancelled')], default='in-cart', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('toyvarient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='babyflamingo.toyvarients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cartsstationary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in-cart', 'in-cart'), ('order-placed', 'order-placed'), ('cancelled', 'cancelled')], default='in-cart', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('stationaryvarient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='babyflamingo.stationaryvarients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cartsdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in-cart', 'in-cart'), ('order-placed', 'order-placed'), ('cancelled', 'cancelled')], default='in-cart', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dressvarient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='babyflamingo.dressvarients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
