# Generated by Django 4.2.5 on 2023-12-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exset1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
